### ISSUE TITLE
Module `sqlite.orm` not found

### ISSUE THREAD

**Issue by MartianGreed** [3rd/time-tracker.nvim#1]
Hey mate ! 

I love what you did there :) But since today extension won't work. 

I'm using lazy nvim and I not sure if git submodules are pulled while installing module.

Can we imagine having the capacity to choose wether we want to use json or sqlite ? 

On my side I'm using files with names by date and with a script I post it to a third party software to track my time.

I'll be happy to contribute but I'm new to lua

**Comment by 3rd** [comment]
Hey, glad you like it!
I just switched it to use SQLite as it was hitting the max length boundary for JSON serialization in Neovim, and it was slow as well. I guess you were writing to a different file every day and you didn't hit the limit?

You can pin it to the previous version if you want to patch it quickly, but you can write a script to dump the entries from the SQLite db as well. What format do you need for the data you post?

Edit: there's a new dependency "3rd/sqlite.nvim", it must error because of that.

**Comment by MartianGreed** [comment]
Yes sure I think I'll ping the previous version and will try to work on the capacity to switch between sqlite and json ! 

Yes indeed I wrote to a different file every day. For now, I didn't wrote my cron to post to `toggl` but I did planned to do it soon.

Adding the dependy fixed the whole thing thank you !

**Comment by 3rd** [comment]
Glad it works! If you share the format you want I can help with the script to dump a JSON from the db.

**Comment by MartianGreed** [comment]
Actually the previous format works well for me !

**Comment by 3rd** [comment]
```sh
#!/usr/bin/env bash
set -euf -o pipefail
IFS=$'\n\t'

DATABASE=time-tracker.db

if [ $# -eq 1 ]; then
  date_filter="$1"
  date_condition="AND date(b.start_time, 'unixepoch') = date('$date_filter')"
else
  date_condition=""
fi

sql_query="
SELECT 
  b.cwd AS cwd,
  b.path AS buffer_path,
  b.start_time AS start,
  b.end_time AS end
FROM buffers b
WHERE 1=1 $date_condition
ORDER BY b.cwd, b.path, b.start_time;"

sqlite3 -json $DATABASE "$sql_query" | jq '
  group_by(.cwd) | map({
    (.[0].cwd): (
      group_by(.buffer_path) | map({
        (.[0].buffer_path): map({start: .start, end: .end})
      }) | add
    )
  }) | add | {roots: .}
'
```

Update the database path and run:
- `./report.sh` to dump everything
- `./report.sh "2024-08-15"` to dump the data for a single day

You need `sqlite3` and `jq` :checkered_flag:

**Comment by MartianGreed** [comment]
Chad ! Thanks for this
